### ISSUE TITLE
DALL-E 3

### ISSUE THREAD

**Issue by wertercatt** [jujumilk3/leaked-system-prompts#12]
https://www.reddit.com/r/ChatGPTPro/comments/171r95u/i_asked_dalle_3_to_generate_images_with_its/

**Comment by jujumilk3** [comment]
omg thx

**Comment by jujumilk3** [comment]
https://github.com/jujumilk3/leaked-system-prompts/commit/61fc9a90c6fd1c3fce96afbdde6adcd6a5590c80
