### ISSUE TITLE
Two (supposed) leaks from Microsoft Copilot (09 March 2024 + 23 March 2024)

### ISSUE THREAD

**Issue by hhmmjjnn** [jujumilk3/leaked-system-prompts#28]
https://old.reddit.com/r/bing/comments/1bapeh7/copilots_initial_prompt_as_of_march_2024
https://old.reddit.com/r/bing/comments/1blltc8/copilots_current_system_prompt_23032024

**Comment by jujumilk3** [comment]
https://github.com/jujumilk3/leaked-system-prompts/pull/29

Thx but Those look very same, so I handled them as one file.
