### ISSUE TITLE
Discord Clyde leak collection

### ISSUE THREAD

**Issue by wertercatt** [jujumilk3/leaked-system-prompts#5]
https://pastebin.com/NRafbjqS

https://twitter.com/itsjustCaio/status/1680046133102493696

https://twitter.com/Spaceguy5/status/1680373304970948610

https://twitter.com/blahaj_in_NYC/status/1680640982432329731

https://twitter.com/localhost_5173/status/1659460678858723329

https://gist.github.com/ayebrian/4385a1fbf1dba6784704dc87cc483f9e

https://gist.github.com/dhd5076/9db8e44947c6226be40b625b68097a5e

https://www.reddit.com/r/discordapp/comments/12to5c7/clyde_ais_initial_prompt/

https://www.reddit.com/r/discordapp/comments/11vtwq1/the_entire_list_of_instructions_for_clyde_ai/

**Comment by jujumilk3** [comment]
Thank you!

https://github.com/jujumilk3/leaked-system-prompts/commit/90d6c7e693a48d8f825ade1748530da16224de07
