### ISSUE TITLE
MS Copilot leaked prompt

### ISSUE THREAD

**Issue by iamhenry** [jujumilk3/leaked-system-prompts#53]
https://gist.github.com/theJayTea/c1c65c931888327f2bad4a254d3e55cb

https://www.reddit.com/r/ArtificialInteligence/comments/1hhyt1y/i_extracted_microsoft_copilots_system/

**Comment by jujumilk3** [comment]
https://github.com/jujumilk3/leaked-system-prompts/commit/d3d9c555b09a023874b5bd71be37f13f3287e315

Thank you so much!
