### ISSUE TITLE
remoteli.io

### ISSUE THREAD

**Issue by wertercatt** [jujumilk3/leaked-system-prompts#7]
https://twitter.com/remoteli_io/status/1570547034159042560

**Comment by jujumilk3** [comment]
I need to know what the question was

**Comment by wertercatt** [comment]
![image](https://github.com/jujumilk3/leaked-system-prompts/assets/7116755/ed3c051c-447b-4b11-8571-5d80ba9e63bb)

**Comment by jujumilk3** [comment]
https://github.com/jujumilk3/leaked-system-prompts/commit/f36478c28cb8f293f6af55132aafbedd8e81064a

thx
